---

- hosts: all
  become: true
  tasks:

    - name: update package index
      apt:
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2
        state: latest

    - name: install htop package
      apt:
        name: htop
        state: latest