---

- hosts: all
  become: true
  tasks:

    - name: update package index
      apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian'] and ansible_distribution_version == '20.04'

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: install htop package
      apt:
        name: htop
        state: latest
      when: ansible_distribution == 'Ubuntu'




    - name: update package index
      dnf:
        update_cache: yes
      when: ansible_distribution in ['CentOS'] and ansible_distribution_version == '8'

    - name: install apache2 package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: add php support for centos
      dnf:
        name: php
        state: latest
      when: ansible_distribution == 'CentOS'