---

- hosts: aws
  become: yes
  tasks:

    - name: copy operational files
      tags: copy_files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '/opt/source_refresh.sh', dest: '/opt/source_refresh.sh' }
        - { src: '/opt/maven_exports.sh', dest: '/opt/maven_exports.sh' }

    - name: add privileges for files
      tags: add_privileges_for_files
      command:
        cmd: 'chmod 774 /opt/network_collector.sh /opt/maven_exports.sh'


    - name: install jdk
      tags: install_jdk
      apt:
        name:
          - openjdk-17-jdk-headless

    - name: add default for java
      tags: add_java_default
      command:
        cmd: 'update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1'

    - name: add default for javac
      tags: add_javac_default
      command:
        cmd: 'update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1'


    - name: check if JAVA_HOME in global env conf
      tags: check_java_global_env_variable
      lineinfile:
        path: /etc/environment
        regexp: "JAVA_HOME=*"
        state: absent
      check_mode: yes
      changed_when: false
      register: java_home_existence_in_env_path

    - name: add JAVA_HOME global env variable
      tags: add_java_global_env_variable
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/java-17-openjdk-amd64"'
      when: not java_home_existence_in_env_path.found


    - name: refresh environment
      tags: refresh_env
      command:
        cmd: '/bin/bash /opt/source_refresh.sh'


    - name: check the maven installation file exist
      tags: check_maven_installation_file_exist
      stat:
        path: /opt/apache-maven-3.8.6-bin.tar.gz
      register: maven_installer_existence

    - name: install maven archive
      tags: install_maven
      command:
        cmd: 'wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz -P /opt'
      when: not maven_installer_existence.stat.exists


    - name: unpack the maven archive
      tags: unpack_maven_archive
      unarchive:
        src: /opt/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        remote_src: yes


    - name: add default for maven
      tags: add_maven_default
      command:
        cmd: 'update-alternatives --install /usr/bin/maven mvn /opt/apache-maven-3.8.6/bin/mvn 1001'

    - name: add env variable for maven
      tags: add_maven_env_variable
      command:
        cmd: '/bin/bash /opt/maven_exports.sh'

    - name: add privileges for mvn
      tags: add_privileges_for_mvn
      command:
        cmd: 'chmod 755 /opt/apache-maven-3.8.6/bin/mvn /opt/apache-maven-3.8.6/bin/mvnDebug /opt/apache-maven-3.8.6/bin/mvnyjp'


