---

- hosts: remote
  become: yes
  tasks:

    - name: copy bash script to hosts
      tags: copy_bash_script
      copy:
        src: bash_scripts/network_collector.sh
        dest: /opt/network_collector.sh
        owner: ansible
        group: ansible
        mode: 0744


    - name: run script
      tags: run_script
      command: /bin/bash /opt/network_collector.sh > /dev/null 2>&1

    - name: fetch netstat files to workstation
      tags: fetch_netstat_files
      fetch:
        src: "/opt/netstat_{{ ansible_hostname }}.txt"
        dest: /opt/
        flat: yes


    - name: fetch lsof files to workstation
      tags: fetch_lsof_files
      fetch:
        src: "/opt/lsof_{{ ansible_hostname }}.txt"
        dest: /opt/
        flat: yes

- hosts: localhost
  connection: local
  become: yes
  tasks:

    - name: run local script merging outputs from remote hosts
      tags: run_local_script
      shell: "/bin/bash bash_scripts/join_output.sh"

