---

- hosts: aws
  become: true
  tasks:


    - name: set environment variable for compressed file name
      tags: set_file_name
      command: export S3_FILE_TO_UPLOAD="$(date '+%d-%m-%Y')_$(hostname).tar.gz"

    - name: compress the /opt directory
      tags: compress_opt
      archive:
        path: /opt
        dest: /opt/$S3_FILE_TO_UPLOAD
        format: gz


    - name: send file to s3 via aws api
      tags: send_to_s3
      command: aws s3api put-object --bucket opt8backup --key aws/$S3_FILE_TO_UPLOAD --body $S3_FILE_TO_UPLOAD


    - name: create summary from AWS S3 resources
      tags: s3_summary_to_file
      command: aws s3 ls s3://opt8backup --recursive --human-readable --summarize >> /opt/s3_summary.txt 2>/dev/null


    - name: check if the compressed file reached the bucked
      tags: check_file_existence_in_bucket
      lineinfile:
        path: /opt/s3_summary.txt
        regexp: "$S3_FILE_TO_UPLOAD"
        state: absent
      check_mode: yes
      changed_when: false
      register: file_existence_in_bucket


    - name: delete the s3 summary if file has been sent successfully
      tags: delete_s3_summary
      when: file_existence_in_bucket.found
      file:
        path: /opt/s3_summary.txt
        state: absent






