---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'


    - name: install updates (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == 'CentOS'

- hosts: server
  become: true
  tasks:

    - name: install apache2 and htop package
      tags: apache,ubuntu
      apt:
        name:
          - apache2
          - htop
        state: latest
      when: ansible_distribution == 'Ubuntu'


    - name: install apache2 and php package
      tags: apache,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == 'CentOS'


- hosts: vm
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      tags: mariadb,ubuntu
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: install mariadb package (Ubuntu)
      tags: mariadb,centos
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == 'Ubuntu'

- hosts: aws
  become: true
  tasks:

    - name: install service on aws host
      tags: aws,service
      service:
        name: httpd
        status: started
      when: ansible_distribution == 'CentOS'